language: julia
julia:
  - release
  - nightly
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.clone("https://github.com/r9y9/MelGeneralizedCepstrums.jl"); Pkg.clone("https://github.com/r9y9/SPTK.jl"); Pkg.build("SPTK"); Pkg.test("SynthesisFilters", coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("SynthesisFilters")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
